---
title: "Heart Prediction Model"
author: "Farrah Johnson and Mariam Ikram"
date: "2026-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
```

```{r}
heart <- read.csv("heart.csv")
glimpse(heart)
```



```{r, include = FALSE}

# takes you to the full database without including it in the knit

view(heart)
```

```{r}
names(heart)
range(heart$Age)
```




```{r clean_comparisons}

# Pulls out necessary data and changes the heart disease to a string to make it more decipherable 
# The 0 and 1 values in heartdisease instead of yes and no was driving me crazy. I cleaned it up and stored it in a variable.

heart_clean <- heart %>%
  mutate(HeartDisease = factor(HeartDisease,
                               levels = c(0, 1),
                               labels = c("No", "Yes")))

set.seed(123)
random_sample <- heart_clean %>%
  sample_n(20)
#I set a seed here so the data we're pulling is more random, as head(20) will only pull the first 20. 


random_sample %>%
  select(Age, Sex, HeartDisease, ExerciseAngina, ST_Slope, Oldpeak) %>%

  arrange(Age) %>%
  head(20)

# gives an average for necessary data for a better comparison


heart_clean %>%
  select(Age, Sex, HeartDisease, ExerciseAngina, ST_Slope, Oldpeak) %>%
  
  group_by(HeartDisease) %>%
  summarise("Average Age" = mean(Age),
            "Old Peak" = mean(Oldpeak))






```

```{r boxplot_correlations}


# What seems to be the highest correlation among these factors with heart disease?

# ST slope, exercise level, & Oldpeak have the highest correlation. ST slope is the segment on an ECG that shows when the heart rate drops below the baseline while under physical stress, with the slope telling us the direction of that drop (depression). The oldpeak measures the drop in a numerical value. 
library(ggthemes)

# I just discovered ggthemes, gonna play with this a bit

ggplot(heart_clean, aes(x = factor(HeartDisease), y = Oldpeak, fill = factor(HeartDisease))) +
  geom_boxplot(alpha = 0.5) +
  labs(title = "Oldpeak Distribution with Heart Disease",
       x = "Heart ") +
  theme_minimal()





```

```{r}
#double checking correlation

cor(heart[, sapply(heart, is.numeric)])["HeartDisease", ]





```




























